# Generated by Django 3.1.5 on 2021-03-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210211_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_id',
        ),
    ]
