# Generated by Django 3.1.5 on 2021-03-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210310_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image_url',
        ),
    ]
