# Generated by Django 3.1.5 on 2021-02-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210219_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=111111, max_length=32),
            preserve_default=False,
        ),
    ]
