# Generated by Django 3.1.5 on 2021-02-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210219_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='img_file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
