# Generated by Django 3.1.5 on 2021-02-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_stripe_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='target_audience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
