# Generated by Django 3.1.5 on 2021-02-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20210225_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='img_file',
            field=models.ImageField(default='{{ MEDIA_URL }}noimage.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='useful_links',
            field=models.CharField(blank=True, default='None', max_length=99999, null=True),
        ),
    ]
