# Generated by Django 3.1.5 on 2021-02-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20210227_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='useful_links',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
    ]
