# Generated by Django 3.1.5 on 2021-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20210227_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='img_file',
            field=models.ImageField(default='noimage.png', null=True, upload_to=''),
        ),
    ]
